name: Build parcel production

on:
  push:
    branches: ["production"]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: ./.github/workflows/cache_npm.yml
      - name: Install & Build
        run: |
          git switch production
          npm install
          npm run build
      - name: Push Production Build
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git add .
          git commit --allow-empty -m "Parcel build"
          git push -f origin production