name: Production to markets

on:
  push:
    branches: ["production"]
  workflow_dispatch:

jobs:
  build_parcel_production:
    uses: ./.github/workflows/build_parcel_production.yml

  build:
    needs: build_parcel_production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        market_branch: ["production-int"]

    steps:
      - uses: actions/checkout@v3

      - name: Merge changes to Market branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: production
          target_branch: ${{ matrix.market_branch }}
          github_token: ${{ secrets.github_token }}