name: Sync Fork with Upstream

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add Upstream and Fetch
        run: |
          git remote add upstream git@github.com:Shopify/dawn.git
          git fetch upstream
          git checkout main
          git merge upstream/main --ff-only || echo "No new updates"

      - name: Push Changes
        run: git push origin main
